version: "3.8"

services:
  #Strapi backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vertex-strapi-backend
    restart: always
    ports:
      - "1337:1337"
    environment:
      HOST: 0.0.0.0
      PORT: 1337

      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_FILENAME: ${DATABASE_FILENAME}
      NODE_ENV: production
    volumes:
      - ./backend/.tmp:/opt/app/.tmp

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vertex-nextjs-frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - nextjs-subscribers:/app
    depends_on:
      - backend

volumes:
  nextjs-subscribers:
